<?xml version="1.0" encoding="utf-8"?><Database Name="dmaa0913_4Sem_Group4" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=kraka.ucn.dk;Initial Catalog=dmaa0913_4Sem_Group4;Persist Security Info=True;User ID=dmaa0913_4Sem_Group4" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="dmaa0913_4Sem_Group4ConnectionString" Provider="System.Data.SqlClient" />
</Database>